
#ifndef RTCONFIG_PREINC_H__
#define RTCONFIG_PREINC_H__

/* Automatically generated file; DO NOT EDIT. */
/* RT-Thread pre-include file */

#define BLHS_SUPPORT
#define COMPONENT_55500
#define COMPONENT_55500A1
#define COMPONENT_APP_KIT_PSE84_EVAL_EPC2
#define COMPONENT_CM33
#define COMPONENT_CM33_0
#define COMPONENT_CYW55513_MOD_PSE84_SOM
#define COMPONENT_Debug
#define COMPONENT_GCC_ARM
#define COMPONENT_GFXSS
#define COMPONENT_HCI_UART
#define COMPONENT_MTB_DEVICE_SUPPORT
#define COMPONENT_MTB_HAL
#define COMPONENT_MW_ASYNC_TRANSFER
#define COMPONENT_MW_BT_FW_IFX_CYW55500A1
#define COMPONENT_MW_CMSIS
#define COMPONENT_MW_CORE_LIB
#define COMPONENT_MW_CORE_MAKE
#define COMPONENT_MW_MTB_DSL_PSE8XXGP
#define COMPONENT_MW_MTB_IPC
#define COMPONENT_MW_MTB_SRF
#define COMPONENT_MW_SE_RT_SERVICES_UTILS
#define COMPONENT_NON_SECURE_DEVICE
#define COMPONENT_PSE84
#define COMPONENT_SM
#define COMPONENT_SOFTFP
#define COMPONENT_WIFI_INTERFACE_SDIO
#define COMPONENT_wlbga_iPA_sLNA_ANT0_LHL_XTAL_IN
#define CORE_NAME_CM33_0 1
#define CYBSP_MCUBOOT_HEADER_SIZE 0x400
#define CYBSP_WIFI_WL_HOSTWAKE_DRIVE_MODE MTB_HAL_GPIO_DRIVE_OPENDRAINDRIVESLOW
#define CYBSP_WIFI_WL_HOSTWAKE_INIT_STATE WHD_TRUE
#define CY_APPNAME_proj_cm33_ns
#define CY_PDL_FLASH_BOOT
#define CY_RETARGET_IO_CONVERT_LF_TO_CRLF
#define CY_SUPPORTS_DEVICE_VALIDATION
#define CY_TARGET_BOARD APP_KIT_PSE84_EVAL_EPC2
#define CY_WIFI_COUNTRY WHD_COUNTRY_UNITED_STATES
#define DEBUG
#define FLASH_BOOT
#define PSE846GPS2DBZC4A
#define RT_USING_LIBC
#define RT_USING_NEWLIBC
#define TARGET_APP_KIT_PSE84_EVAL_EPC2
#define TRXV5
#define _POSIX_C_SOURCE 1
#define __RTTHREAD__

#endif /*RTCONFIG_PREINC_H__*/
