import rtconfig
from building import *
import os

cwd  = GetCurrentDir()
ports_root = os.path.abspath(os.path.join(cwd, '..', 'libraries', 'Common', 'board', 'ports')).replace('\\', '/')
common_root = os.path.abspath(os.path.join(cwd, '..', 'libraries', 'Common')).replace('\\', '/')
usb_port = ports_root + '/usb'
path = [
    cwd,
    usb_port,
    common_root + '/deepcraft_ai/include',
]
src  = Glob('*.c')

if GetDepend(['USE_EXECUTORCH_TINYCNN']):
    disabled_ai_sources = ['uvc_ai_app.c', 'uvc_ai_ethosu_rtos.c']
    src = [item for item in src if os.path.basename(str(item)) not in disabled_ai_sources]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
