import os
import sys
import rtconfig
import platform
import subprocess
import uuid

if os.path.exists('rt-thread'):
    RTT_ROOT = os.path.normpath(os.getcwd() + '/rt-thread')
else:
    RTT_ROOT = os.path.normpath(os.getcwd() + '/../../rt-thread')

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
try:
    from building import *
except Exception as e:
    print("Error message:", e)
    print('Cannot found RT-Thread root directory, please check RTT_ROOT')
    print(RTT_ROOT)
    sys.exit(-1)

TARGET = 'rt-thread.' + rtconfig.TARGET_EXT

DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)

if rtconfig.PLATFORM in ['iccarm']:
    env.Replace(CCCOM = ['$CC $CFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS -o $TARGET $SOURCES'])
    env.Replace(ARFLAGS = [''])
    env.Replace(LINKCOM = env["LINKCOM"] + ' --map rt-thread.map')

Export('RTT_ROOT')
Export('rtconfig')
Export('env')

# Resolve path to shared BSP sources so we can add the generated headers once.
if os.path.exists(os.path.join(os.getcwd(), "libs")):
    libs_source = 'libs'
else:
    libs_source = '../libs'

libs_root = os.path.abspath(os.path.join(os.getcwd(), libs_source))
libs_bsp_dir = os.path.join(libs_root, 'TARGET_APP_KIT_PSE84_EVAL_EPC2')

if os.path.isdir(libs_bsp_dir):
    env.AppendUnique(CPPPATH=[
        libs_bsp_dir,
        os.path.join(libs_bsp_dir, 'config'),
        os.path.join(libs_bsp_dir, 'config', 'GeneratedSource'),
        os.path.join(libs_bsp_dir, 'bluetooth'),
    ])

SDK_ROOT = os.path.abspath('./')
if os.path.exists(SDK_ROOT + '/libraries/components'):
    libraries_path_prefix = SDK_ROOT + '/libraries/components'
else:
    libraries_path_prefix = os.path.dirname(SDK_ROOT) + '/../libraries/components'

SDK_LIB = libraries_path_prefix
Export('SDK_LIB')

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=False)

IFX_library = 'Packages'
rtconfig.BSP_LIBRARY_TYPE = IFX_library

# set spawn
def ourspawn(sh, escape, cmd, args, e):
    filename = os.path.join('./', 'build', str(uuid.uuid4()))
    newargs = ' '.join(args[1:])
    cmdline = cmd + " " + newargs
    if (len(cmdline) > 16 * 1024):
        f = open(filename, 'w')
        f.write(' '.join(args[1:]).replace('\\', '/'))
        f.close()
        # exec
        cmdline = cmd + " @" + filename
    proc = subprocess.Popen(cmdline, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE, shell = False, env = e)
    data, err = proc.communicate()
    rv = proc.wait()
    def res_output(_output, _s):
        if len(_s):
            if isinstance(_s, str):
                _output(_s)
            elif isinstance(_s, bytes):
                _output(str(_s, 'UTF-8'))
            else:
                _output(str(_s))
    res_output(sys.stderr.write, err)
    res_output(sys.stdout.write, data)
    if os.path.isfile(filename):
        os.remove(filename)
    return rv

if platform.system() == 'Windows':
    env['SPAWN'] = ourspawn

# Add project libs with VariantDir
if os.path.exists(os.path.join(os.getcwd(), "libs")):
    env.VariantDir('build/libs', 'libs', duplicate=0)
else:
    env.VariantDir('build/libs', '../libs', duplicate=0)
    objs.extend(SConscript('../libs/SConscript', variant_dir='build/libs', duplicate=0))

if os.path.exists(os.path.join(os.getcwd(), "libraries")):
    # Set VariantDir for libraries
    env.VariantDir('build/libraries/HAL_Drivers', 'libraries/HAL_Drivers', duplicate=0)
    env.VariantDir('build/libraries/components', 'libraries/components', duplicate=0)
    env.VariantDir('build/libraries/M55_Config/board', 'libraries/M55_Config/board', duplicate=0)
    env.VariantDir('build/libraries/Common/board', 'libraries/Common/board', duplicate=0)
    env.VariantDir('build/libraries/Common/deepcraft_ai', 'libraries/Common/deepcraft_ai', duplicate=0)

    objs.extend(SConscript('libraries/HAL_Drivers/SConscript', variant_dir='build/libraries/HAL_Drivers', duplicate=0))
    objs.extend(SConscript('libraries/components/Infineon_cmsis-latest/SConscript', variant_dir='build/libraries/components/Infineon_cmsis-latest', duplicate=0))
    objs.extend(SConscript('libraries/components/Infineon_core-lib-latest/SConscript', variant_dir='build/libraries/components/Infineon_core-lib-latest', duplicate=0))
    objs.extend(SConscript('libraries/components/mtb-device-support-pse8xxgp/hal/SConscript', variant_dir='build/libraries/components/mtb-device-support-pse8xxgp/hal', duplicate=0))
    objs.extend(SConscript('libraries/components/mtb-device-support-pse8xxgp/pdl/SConscript', variant_dir='build/libraries/components/mtb-device-support-pse8xxgp/pdl', duplicate=0))
    objs.extend(SConscript('libraries/components/async-transfer/SConscript', variant_dir='build/libraries/components/async-transfer', duplicate=0))
    objs.extend(SConscript('libraries/components/mtb-device-support-pse8xxgp/device-utils/syspm/SConscript', variant_dir='build/libraries/components/mtb-device-support-pse8xxgp/device-utils/syspm', duplicate=0))
    objs.extend(SConscript('libraries/components/serial-memory/SConscript', variant_dir='build/libraries/components/serial-memory', duplicate=0))
    objs.extend(SConscript('libraries/components/Infineon_retarget-io-latest/SConscript', variant_dir='build/libraries/components/Infineon_retarget-io-latest', duplicate=0))
    objs.extend(SConscript('libraries/components/ASRC/SConscript', variant_dir='build/libraries/components/ASRC', duplicate=0))
    objs.extend(SConscript('libraries/components/mtb-srf/SConscript', variant_dir='build/libraries/components/mtb-srf', duplicate=0))
    objs.extend(SConscript('libraries/components/mtb-ipc/SConscript', variant_dir='build/libraries/components/mtb-ipc', duplicate=0))
    objs.extend(SConscript('libraries/components/littlefs/SConscript', variant_dir='build/libraries/components/littlefs', duplicate=0))
    objs.extend(SConscript('libraries/components/SConscript', variant_dir='build/libraries/components', duplicate=0))
    objs.extend(SConscript('libraries/Common/board/SConscript', variant_dir='build/libraries/Common/board', duplicate=0))
    objs.extend(SConscript('libraries/Common/deepcraft_ai/SConscript', variant_dir='build/libraries/Common/deepcraft_ai', duplicate=0))
else:
    # Set VariantDir for external libraries
    env.VariantDir('build/libraries/HAL_Drivers', '../../libraries/HAL_Drivers', duplicate=0)
    env.VariantDir('build/libraries/components', '../../libraries/components', duplicate=0)
    env.VariantDir('build/libraries/M55_Config/board', '../../libraries/M55_Config/board', duplicate=0)
    env.VariantDir('build/libraries/Common/board', '../../libraries/Common/board', duplicate=0)
    env.VariantDir('build/libraries/Common/deepcraft_ai', '../../libraries/Common/deepcraft_ai', duplicate=0)

    objs.extend(SConscript('../../libraries/HAL_Drivers/SConscript', variant_dir='build/libraries/HAL_Drivers', duplicate=0))
    objs.extend(SConscript('../../libraries/components/Infineon_cmsis-latest/SConscript', variant_dir='build/libraries/components/Infineon_cmsis-latest', duplicate=0))
    objs.extend(SConscript('../../libraries/components/Infineon_core-lib-latest/SConscript', variant_dir='build/libraries/components/Infineon_core-lib-latest', duplicate=0))
    objs.extend(SConscript('../../libraries/components/mtb-device-support-pse8xxgp/hal/SConscript', variant_dir='build/libraries/components/mtb-device-support-pse8xxgp/hal', duplicate=0))
    objs.extend(SConscript('../../libraries/components/mtb-device-support-pse8xxgp/pdl/SConscript', variant_dir='build/libraries/components/mtb-device-support-pse8xxgp/pdl', duplicate=0))
    objs.extend(SConscript('../../libraries/components/async-transfer/SConscript', variant_dir='build/libraries/components/async-transfer', duplicate=0))
    objs.extend(SConscript('../../libraries/components/mtb-device-support-pse8xxgp/device-utils/syspm/SConscript', variant_dir='build/libraries/components/mtb-device-support-pse8xxgp/device-utils/syspm', duplicate=0))
    objs.extend(SConscript('../../libraries/components/serial-memory/SConscript', variant_dir='build/libraries/components/serial-memory', duplicate=0))
    objs.extend(SConscript('../../libraries/components/Infineon_retarget-io-latest/SConscript', variant_dir='build/libraries/components/Infineon_retarget-io-latest', duplicate=0))
    objs.extend(SConscript('../../libraries/components/ASRC/SConscript', variant_dir='build/libraries/components/ASRC', duplicate=0))
    objs.extend(SConscript('../../libraries/components/mtb-srf/SConscript', variant_dir='build/libraries/components/mtb-srf', duplicate=0))
    objs.extend(SConscript('../../libraries/components/mtb-ipc/SConscript', variant_dir='build/libraries/components/mtb-ipc', duplicate=0))
    objs.extend(SConscript('../../libraries/components/littlefs/SConscript', variant_dir='build/libraries/components/littlefs', duplicate=0))
    objs.extend(SConscript('../../libraries/components/SConscript', variant_dir='build/libraries/components', duplicate=0))
    objs.extend(SConscript('../../libraries/Common/board/SConscript', variant_dir='build/libraries/Common/board', duplicate=0))
    objs.extend(SConscript('../../libraries/Common/deepcraft_ai/SConscript', variant_dir='build/libraries/Common/deepcraft_ai', duplicate=0))

# make a building
DoBuilding(TARGET, objs)
