from building import *

cwd = GetCurrentDir()
project_root = Dir('#').abspath.replace('\\', '/')
cherryusb_root = project_root + '/libraries/components/CherryUSB-1.6.0'
build_uvc_from_source = GetDepend(['RT_CHERRYUSB_HOST_BUILD_FROM_SOURCE'])

src = [
    'usbh_uvc_app.c',
    'usbh_uvc_display.c',
    'tjpgd.c',
]

cpp_path = [
    cwd,
    project_root + '/applications',
]

libs = []
libpath = []

if build_uvc_from_source:
    src += [
        'usbh_uvc_port.c',
        'usbh_uvc_stream.c',
    ]
    cpp_path += [
        cherryusb_root + '/common',
        cherryusb_root + '/core',
        cherryusb_root + '/class/hub',
        cherryusb_root + '/class/video',
        cherryusb_root + '/third_party/cherrymp',
        cherryusb_root + '/port/dwc2',
    ]
else:
    libpath = [cwd]
    libs = ['usbh_uvc']

group = DefineGroup(
    'UsbUvc',
    src,
    depend=['RT_CHERRYUSB_HOST_VIDEO'],
    CPPPATH=cpp_path,
    LIBPATH=libpath,
    LIBS=libs,
)

Return('group')
